os: Visual Studio 2017
version: "{build}"
configuration: Release
environment:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    RunCoverage: true
install:
  - ps: choco install gitversion.portable -pre -y -r --no-progress
  - ps: choco install codecov -pre -y -r --no-progress --version 1.0.5
before_build:
  - dotnet restore
  - ps: gitversion /output buildserver /updateAssemblyInfo
build:
    verbosity: minimal
before_test:
  - ps: |
      # Install OpenCover
      nuget install -OutputDirectory packages -Version 4.6.519 OpenCover
test_script:
  - ps: |
      # Run tests & coverage
      $dotnetPath=(Join-Path $env:ProgramFiles (Join-Path dotnet dotnet.exe))
      .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"$dotnetPath" `
         -targetargs:"test" -output:"coverage.xml" -oldstyle `
         -filter:"+[Ward*]* -[Ward.DnsClient]Asn1.* -[Ward.*.Tests]*" `
         -excludebyattribute:*DebuggerStepThrough*
      codecov -f "coverage.xml"
after_test:
  - ps: |
      # Run some benchmarks
      Push-Location .\benchmarks\Ward.Benchmarks
      dotnet run -c Release -f net461 -- --attribute=RunInCI
      Pop-Location
  - dotnet msbuild /t:Restore,Pack /p:PackageOutputPath=artifacts /p:Version="%GitVersion_NuGetVersion%"
  - dotnet pack src\Ward.Console\Ward.Console.csproj /p:Version="%GitVersion_NuGetVersion%"
artifacts:
  - path: "**\\artifacts\\**\\*.*"
  - path: "_artifacts\\**"
  - path: ".\\benchmarks\\Ward.Benchmarks\\BenchmarkDotNet.Artifacts"
    name: Benchmark Artifacts
    type: zip
  - path: coverage
    name: Coverage Report
    type: zip
